### ISSUE TITLE
binutils_install.py: subprocess has no attribute 'run'

### ISSUE THREAD

**Issue by NiklasRosenstein** [winksaville/vendor-install-tools#2]
```
Traceback (most recent call last):
  File "./install.py", line 53, in <module>
    installer.install()
  File "/home/niklas/Desktop/vendor-install-tools-master/binutils_install.py", line 89, in install
    subprocess.run(configureCmd,
AttributeError: 'module' object has no attribute 'run'
```

**Comment by NiklasRosenstein** [comment]
Same in `utils.py`. I also get

```
Traceback (most recent call last):
  File "./install.py", line 53, in <module>
    installer.install()
  File "/home/niklas/Desktop/vendor-install-tools-master/binutils_install.py", line 95, in install
    utils.bash('make install')
  File "/home/niklas/Desktop/vendor-install-tools-master/utils.py", line 58, in bash
    check=True)
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
TypeError: __init__() got an unexpected keyword argument 'check'
```

**Comment by winksaville** [comment]
I'm using Python 3.5 and the subprocess
https://docs.python.org/3/library/subprocess.html command has a run
method, you need to upgrade :)

"The run()
https://docs.python.org/3/library/subprocess.html#subprocess.run function
was added in Python 3.5; if you need to retain compatibility with older
versions, see the Older high-level API
https://docs.python.org/3/library/subprocess.html#call-function-trio
 section."

**Comment by winksaville** [comment]
Upgrade to Python 3.5

**Comment by NiklasRosenstein** [comment]
I see, didn't know that this function was added in 3.5. Thanks :)

**Comment by winksaville** [comment]
Learn something new everyday:)
