### ISSUE TITLE
Installation of binutils for host fails on Travis [branch:NiklasRosenstein]

### ISSUE THREAD

**Issue by NiklasRosenstein** [winksaville/vendor-install-tools#5]
```
236.26s$ ./.travis/wait ./install ct-ng-install --ct-ng-install:target=arm-eabi --ct-ng-install:prefix=.travis/
[.travis-wait]: Started (120s interval)
crosstools-ng 1.22.0 already installed
installing arm-eabi with crosstool-ng to '.travis/cross/arm-eabi'
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20160101.202920
[INFO ]  Building environment variables
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[INFO ]  Retrieving needed toolchain components' tarballs: done in 62.51s (at 01:04)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[INFO ]  Extracting and patching toolchain components: done in 37.20s (at 01:41)
[INFO ]  =================================================================
[INFO ]  Installing GMP for host
[02:00] \ [.travis-wait]: .
[INFO ]  Installing GMP for host: done in 35.57s (at 02:16)
[INFO ]  =================================================================
[INFO ]  Installing MPFR for host
[INFO ]  Installing MPFR for host: done in 32.69s (at 02:49)
[INFO ]  =================================================================
[INFO ]  Installing ISL for host
[INFO ]  Installing ISL for host: done in 26.64s (at 03:16)
[INFO ]  =================================================================
[INFO ]  Installing MPC for host
[INFO ]  Installing MPC for host: done in 13.20s (at 03:29)
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[ERROR]    checking whether it is safe to define __EXTENSIONS__... make[3]: *** [configure-ld] Error 1
[ERROR]    make[2]: *** [all] Error 2
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_binutils_backend[scripts/build/binutils/binutils.sh@240]
[ERROR]  >>        called from: do_binutils_for_host[scripts/build/binutils/binutils.sh@105]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/travis/opt/share/doc/crosstool-ng/crosstool-ng-1.22.0/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 3:56.01)
[03:56] / make[1]: *** [build] Error 2
make: *** [build.4] Error 2
Traceback (most recent call last):
  File "/home/travis/build/winksaville/vendor-install-tools/installlib.py", line 297, in install
    runpy.run_path(installer['script'], {'settings': settings}, run_name='__main__')
  File "/opt/python/2.7.9/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/python/2.7.9/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/python/2.7.9/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "installers/ct-ng-install.py", line 61, in <module>
    main()
  File "installers/ct-ng-install.py", line 57, in main
    installlib.run(['ct-ng', 'build.4'])
  File "/home/travis/build/winksaville/vendor-install-tools/installlib.py", line 136, in run
    result.check_returncode()
  File "/home/travis/build/winksaville/vendor-install-tools/installlib.py", line 90, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout, self.stderr)
CalledProcessError: Command ['ct-ng', 'build.4'] exited with non-zero exit status 2
error installing ct-ng-install. quit
[.travis-wait]: Killed
./.travis/wait: line 19: 101972 Terminated              _travis_wait
The command "./.travis/wait ./install ct-ng-install --ct-ng-install:target=arm-eabi --ct-ng-install:prefix=.travis/" exited with 1.
Done. Your build exited with 1.
```

**Comment by winksaville** [comment]
No longer supporting travis, I'm now using circleci as my test platform. Will add a bug to have this test on circleci.
